directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
### These checkov checks have been skipped because these features are in future releases
- CKV_AWS_144 #Ensure that S3 bucket has cross-region replication enabled
- CKV_AWS_300 #Ensure S3 lifecycle configuration sets period for aborting failed uploads
- CKV_TF_1 #Ensure Terraform module sources use a commit hash
- CKV_AWS_21 #Ensure all data stored in the S3 bucket have versioning enabled
- CKV2_AWS_65 #Ensure access control lists for S3 buckets are disabled
- CKV2_AWS_67 #Ensure AWS S3 bucket encrypted with Customer Managed Key (CMK) has regular rotation
