directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
### These checkov checks have been skipped because these features are in future releases
- CKV_AWS_144 #Ensure that S3 bucket has cross-region replication enabled
- CKV2_AWS_62 #"Ensure S3 buckets should have event notifications enabled"
- CKV2_AWS_61 #"Ensure that an S3 bucket has a lifecycle configuration"
